name: message-passing-neural-network
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7.6
  - tox=3.14.3
  - numpy=1.17.4
  - pandas=1.0.3
  - pytorch=1.5.0
  - torchvision=0.6.0',
  - psycopg2=2.8.6',
  - setuptools=46.0.0
  - click
  - tqdm